### ISSUE TITLE
Redmine 3.4.x Settings compatibility

### ISSUE THREAD

**Issue by gruenwaldlk** [KadVenku/redmine_omniauth_gitlab#1]
Update the settings syntax to be compatible with Redmine 3.4.x

**Comment by KadVenku** [comment]
Should be fixed in 42c377eaa13a3ef0c841e3424eb246c2f08981c1

**Comment by gruenwaldlk** [comment]
Issue fixed: 42c377eaa13a3ef0c841e3424eb246c2f08981c1
